apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /php_fpm_ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 2
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /php_fpm_ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: conf.d/default.conf
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
      - name: php-fpm
        image: php:7.1-fpm-alpine
        volumeMounts:
        - name: php-fpm-conf
          mountPath: /usr/local/etc/php-fpm.conf
          subPath: php-fpm.conf
        - name: php-fpm-conf
          mountPath: /usr/local/etc/php-fpm.d/www.conf
          subPath: php-fpm.d/www.conf
        - name: php-fpm-conf
          mountPath: /usr/local/etc/php/php.ini
          subPath: php/php.ini
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          defaultMode: 420
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: default.k8s.conf
            path: conf.d/default.conf
      - name: php-fpm-conf
        configMap:
          name: php-fpm-conf
          defaultMode: 420
          items:
          - key: php-fpm.conf
            path: php-fpm.conf
          - key: www.conf
            path: php-fpm.d/www.conf
          - key: php.ini
            path: php/php.ini